### ISSUE TITLE
Filesystem Detail Chart shows incorrect units for storage statistics 

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/old-gui#22]
The storage metrics on the filesystem detail page and targets should be calculated using the number-formatters algorithm. Unfortunately, the old gui will not allow the repo to be included and bundled, so for now I think it makes sense to replace the functionality in misc.js with the logic in number-formatters.

**Comment by jgrund** [comment]
> for now I think it makes sense to replace the functionality in misc.js with the logic in number-formatters.

Just add the number-formatters file into https://github.com/whamcloud/old-gui/tree/master/static/js/lib

**Comment by johnsonw** [comment]
Sounds good.

**Comment by johnsonw** [comment]
![image](https://user-images.githubusercontent.com/1100657/52864094-6de88d80-3107-11e9-9d53-6b823d369ae7.png)
