### ISSUE TITLE
Filesystem detail chart does not poll.

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/old-gui#24]
When creating a filesystem, we will poll the filesystem detail url every 5 seconds until we receive data. Once a response with data is received, the endpoint is no longer polled. Once data is populated, the chart is rendered using the storage metrics. In some cases, however, the endpoint may return a set of data as the metrics are still being populated. The end result of this is that the chart displays inaccurate storage statistics. If the user waits for a moment and then refreshes the page, the correct storage metrics will be displayed. For example:

When endpoint receives data:
![image](https://user-images.githubusercontent.com/1100657/52866286-58c22d80-310c-11e9-9b6b-f1d642fcfbd5.png)

After refreshing the page:
![image](https://user-images.githubusercontent.com/1100657/52866334-6b3c6700-310c-11e9-9405-99b394a44fbf.png)

**Comment by jgrund** [comment]
Given this is a minor (albeit annoying) bug, we should pend on this until we update the page to be realtime like the rest of the app.

**Comment by johnsonw** [comment]
I agree. Can we keep this ticket open to reference for any tickets that come in?

**Comment by jgrund** [comment]
Sure.
